package Empleate.domain;
// Generated 12/03/2018 12:06:18 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class Category  implements java.io.Serializable {


     private int idCategory;
     private Category category;
     private String nameCategory;
     private Set<Category> categories = new HashSet<Category>(0);
     private Set<Jobcategory> jobcategories = new HashSet<Jobcategory>(0);
     private Set<Offercategory> offercategories = new HashSet<Offercategory>(0);

    public Category() {
    }

	
    public Category(int idCategory) {
        this.idCategory = idCategory;
    }
    public Category(int idCategory, Category category, String nameCategory, Set<Category> categories, Set<Jobcategory> jobcategories, Set<Offercategory> offercategories) {
       this.idCategory = idCategory;
       this.category = category;
       this.nameCategory = nameCategory;
       this.categories = categories;
       this.jobcategories = jobcategories;
       this.offercategories = offercategories;
    }

    public Category(int idCategory, Category category, String nameCategory) {
        this.idCategory = idCategory;
        this.category = category;
        this.nameCategory = nameCategory;
    }
   
    public int getIdCategory() {
        return this.idCategory;
    }
    
    public void setIdCategory(int idCategory) {
        this.idCategory = idCategory;
    }
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }
    public String getNameCategory() {
        return this.nameCategory;
    }
    
    public void setNameCategory(String nameCategory) {
        this.nameCategory = nameCategory;
    }
    public Set<Category> getCategories() {
        return this.categories;
    }
    
    public void setCategories(Set<Category> categories) {
        this.categories = categories;
    }
    public Set<Jobcategory> getJobcategories() {
        return this.jobcategories;
    }
    
    public void setJobcategories(Set<Jobcategory> jobcategories) {
        this.jobcategories = jobcategories;
    }
    public Set<Offercategory> getOffercategories() {
        return this.offercategories;
    }
    
    public void setOffercategories(Set<Offercategory> offercategories) {
        this.offercategories = offercategories;
    }




}


