package Empleate.domain;
// Generated 12/03/2018 12:06:18 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Company generated by hbm2java
 */
public class Company  implements java.io.Serializable {


     private int idCompany;
     private String nameCompany;
     private String email;
     private String phone;
     private String description;
     private Serializable location;
     private String address;
     private Set<Job> jobs = new HashSet<Job>(0);
     private Set<Login> logins = new HashSet<Login>(0);

    public Company() {
    }

	
    public Company(int idCompany) {
        this.idCompany = idCompany;
    }
    public Company(int idCompany, String nameCompany, String email, String phone, String description, Serializable location, String address, Set<Job> jobs, Set<Login> logins) {
       this.idCompany = idCompany;
       this.nameCompany = nameCompany;
       this.email = email;
       this.phone = phone;
       this.description = description;
       this.location = location;
       this.address = address;
       this.jobs = jobs;
       this.logins = logins;
    }

    public Company(int idCompany, String email, String phone, String description, Serializable location, String address) {
        this.idCompany = idCompany;
        this.email = email;
        this.phone = phone;
        this.description = description;
        this.location = location;
        this.address = address;
    }
   
    public int getIdCompany() {
        return this.idCompany;
    }
    
    public void setIdCompany(int idCompany) {
        this.idCompany = idCompany;
    }
    public String getNameCompany() {
        return this.nameCompany;
    }
    
    public void setNameCompany(String nameCompany) {
        this.nameCompany = nameCompany;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Serializable getLocation() {
        return this.location;
    }
    
    public void setLocation(Serializable location) {
        this.location = location;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public Set<Job> getJobs() {
        return this.jobs;
    }
    
    public void setJobs(Set<Job> jobs) {
        this.jobs = jobs;
    }
    public Set<Login> getLogins() {
        return this.logins;
    }
    
    public void setLogins(Set<Login> logins) {
        this.logins = logins;
    }




}


