package Empleate.domain;
// Generated 12/03/2018 12:06:18 AM by Hibernate Tools 4.3.1



/**
 * JobcategoryId generated by hbm2java
 */
public class JobcategoryId  implements java.io.Serializable {


     private int j;
     private int cat;

    public JobcategoryId() {
    }

    public JobcategoryId(int j, int cat) {
       this.j = j;
       this.cat = cat;
    }
   
    public int getJ() {
        return this.j;
    }
    
    public void setJ(int j) {
        this.j = j;
    }
    public int getCat() {
        return this.cat;
    }
    
    public void setCat(int cat) {
        this.cat = cat;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof JobcategoryId) ) return false;
		 JobcategoryId castOther = ( JobcategoryId ) other; 
         
		 return (this.getJ()==castOther.getJ())
 && (this.getCat()==castOther.getCat());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getJ();
         result = 37 * result + this.getCat();
         return result;
   }   


}


