package Empleate.domain;
// Generated 12/03/2018 12:06:18 AM by Hibernate Tools 4.3.1



/**
 * Login generated by hbm2java
 */
public class Login  implements java.io.Serializable {


     private int idLogin;
     private String username;
     private String password;
     private String type_log;
     private int enable;

    public Login() {
        idLogin=-1;
        username="";
        password="";
        type_log="";
        enable=0;
    }

	
    public Login(int idLogin, Company company, Manager manager, Offerer offerer) {
        this.idLogin = idLogin;
    }
    public Login(int idLogin, Company company, Manager manager, Offerer offerer, String username, String password, String type,int enable) {
       this.idLogin = idLogin;
       this.username = username;
       this.password = password;
       this.type_log = type;
       this.enable = enable;
    }
   
    public int getIdLogin() {
        return this.idLogin;
    }
    
    public void setIdLogin(int idLogin) {
        this.idLogin = idLogin;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String passwordLog) {
        this.password = passwordLog;
    }

    public String getType_log() {
        return type_log;
    }

    public void setType_log(String type_log) {
        this.type_log = type_log;
    }
   

    public int getEnable() {
        return enable;
    }

    public void setEnable(int enable) {
        this.enable = enable;
    }




}


