package Empleate.domain;
// Generated 12/03/2018 12:06:18 AM by Hibernate Tools 4.3.1



/**
 * Login generated by hbm2java
 */
public class Login  implements java.io.Serializable {


     private int idLogin;
     private Company company;
     private Manager manager;
     private Offerer offerer;
     private String username;
     private String passwordLog;
     private String type;

    public Login() {
    }

	
    public Login(int idLogin, Company company, Manager manager, Offerer offerer) {
        this.idLogin = idLogin;
        this.company = company;
        this.manager = manager;
        this.offerer = offerer;
    }
    public Login(int idLogin, Company company, Manager manager, Offerer offerer, String username, String passwordLog, String type) {
       this.idLogin = idLogin;
       this.company = company;
       this.manager = manager;
       this.offerer = offerer;
       this.username = username;
       this.passwordLog = passwordLog;
       this.type = type;
    }
   
    public int getIdLogin() {
        return this.idLogin;
    }
    
    public void setIdLogin(int idLogin) {
        this.idLogin = idLogin;
    }
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }
    public Manager getManager() {
        return this.manager;
    }
    
    public void setManager(Manager manager) {
        this.manager = manager;
    }
    public Offerer getOfferer() {
        return this.offerer;
    }
    
    public void setOfferer(Offerer offerer) {
        this.offerer = offerer;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPasswordLog() {
        return this.passwordLog;
    }
    
    public void setPasswordLog(String passwordLog) {
        this.passwordLog = passwordLog;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }




}


