package Empleate.domain;
// Generated 12/03/2018 12:06:18 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import java.util.logging.Logger;

/**
 * Manager generated by hbm2java
 */
public class Manager  implements java.io.Serializable {


     private int idManager;
     private int login;
     private String email;
     private Set<Login> logins = new HashSet<Login>(0);

    public Manager() {
    }

    public Manager(int idManager,int login) {
        this.idManager = idManager;
        this.login=login;
    }
    
    public Manager(int idManager) {
        this.idManager = idManager;
    }
    
    public Manager(int idManager, String email, Set<Login> logins) {
       this.idManager = idManager;
       this.logins = logins;
       this.email = email;
    }
    
     public Manager(int idManager, String email,int login) {
       this.idManager = idManager;
       this.logins = logins;
       this.email = email;
    }
   
    public int getIdManager() {
        return this.idManager;
    }
    
    public void setIdManager(int idManager) {
        this.idManager = idManager;
    }

    public Set<Login> getLogins() {
        return this.logins;
    }
    
    public void setLogins(Set<Login> logins) {
        this.logins = logins;
    }

    public int getLogin() {
        return login;
    }

    public void setLogin(int login) {
        this.login = login;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }
    
    

}


