package Empleate.domain;
// Generated 12/03/2018 12:06:18 AM by Hibernate Tools 4.3.1



/**
 * OffercategoryId generated by hbm2java
 */
public class OffercategoryId  implements java.io.Serializable {


     private int offer;
     private int cat;

    public OffercategoryId() {
    }

    public OffercategoryId(int offer, int cat) {
       this.offer = offer;
       this.cat = cat;
    }
   
    public int getOffer() {
        return this.offer;
    }
    
    public void setOffer(int offer) {
        this.offer = offer;
    }
    public int getCat() {
        return this.cat;
    }
    
    public void setCat(int cat) {
        this.cat = cat;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OffercategoryId) ) return false;
		 OffercategoryId castOther = ( OffercategoryId ) other; 
         
		 return (this.getOffer()==castOther.getOffer())
 && (this.getCat()==castOther.getCat());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getOffer();
         result = 37 * result + this.getCat();
         return result;
   }   


}


